### ISSUE TITLE
Unsubscribe on deploy / Issues when deploy

### ISSUE THREAD

**Issue by jlancasterhmma** [netsmarttech/node-red-contrib-open-protocol#10]
Does this node automatically close the device connection and/or unsubscribe from subscribed MID's when you deploy the project?

I ask because, I am developing a flow that subscribes (last torque result) to a PF4000.
That PF4000 has another server connected to it with subscriptions.
Whenever I deploy my flow's, which is constantly as I am in development, it seems to affect the other connection.
I believe the PF4000 only allows 2 or 3 clients to subscribe, based on what I have seen so far.

To work around the issue I am seeing, I have to manually inject an unsubscribe, then I deploy my flow. I can give further details if needed.
Also, I use the auto subscribe property in the node.

**Comment by gfcittolin** [comment]
Hi
When the flow is deployed, the only thing that happens is to close the connection, no unsubscription is performed. Do you mean, whenever you deploy your flow (and the connection therefore dropped), the other device connected to the PF stops receiving the results, as if it had unsubscribed too?

I've never had or heard of such an issue, and the OpenProtocol manuals don't seem to mention such a behavior. Have you checked out if there's a firmware update available to your controller?

**Comment by jlancasterhmma** [comment]
Do you mean, whenever you deploy your flow (and the connection therefore dropped), the other device connected to the PF stops receiving the results, as if it had unsubscribed too?
_Yes._

I will try to apply any new firmware, as I highly suspect that to be the issue.
I was asking because I was curious the technical details of what happens on deploy.

I have about many controllers I can test with, and of the few I have tried so far; they have 2 different versions of firmware. Oddly enough, the older firmware seems to be more stable. The newer firmware has this issue and is solidy repeatable.

**Comment by gfcittolin** [comment]
> Oddly enough, ...

Not so oddly, unfortunately. I've seen newer firmware versions introducing new bugs so many times already. Sometimes, firmware regression is the way to go. Good luck there, and let me know if you need any other info.
